import {render,screen,within} from '@testing-library/react';import userEvent from '@testing-library/user-event';import {describe,it,expect} from 'vitest';import App from './App';
describe('Session journal',()=>{
 it('shows deterministic totals',()=>{render(<App/>);expect(screen.getByText('$380')).toBeInTheDocument();expect(screen.getAllByRole('row')).toHaveLength(6);});
 it('filters losses',async()=>{render(<App/>);await userEvent.selectOptions(screen.getByLabelText('Show'),'Losses');expect(screen.getAllByRole('row')).toHaveLength(3);});
 it('searches and clears empty state',async()=>{render(<App/>);await userEvent.type(screen.getByLabelText('Find symbol'),'none');expect(screen.getByText('No trades match.')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Clear filters'}));expect(screen.getAllByRole('row')).toHaveLength(6);});
 it('reviews a trade and persists',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:'Review MES at 09:34'}));const d=screen.getByRole('dialog');expect(within(d).getByText('MES at 09:34')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Mark as reviewed'}));expect(screen.getByText('1 of 5 reviewed')).toBeInTheDocument();expect(JSON.parse(localStorage.getItem('clearstep')!).reviewed).toEqual([1]);});
 it('rejects out of bounds risk limit',async()=>{render(<App/>);const i=screen.getByLabelText('Daily loss limit ($)');await userEvent.clear(i);await userEvent.type(i,'0');await userEvent.click(screen.getByRole('button',{name:'Save risk limit'}));expect(screen.getByRole('alert')).toHaveTextContent('Enter a whole-dollar');expect(i).toHaveAttribute('aria-invalid','true');});
 it('saves risk limit and shows boundary',async()=>{render(<App/>);const i=screen.getByLabelText('Daily loss limit ($)');await userEvent.clear(i);await userEvent.type(i,'100');await userEvent.click(screen.getByRole('button',{name:'Save risk limit'}));expect(screen.getByRole('status')).toHaveTextContent('Risk limit saved.');expect(screen.getByText('Limit reached in sample session')).toBeInTheDocument();});
 it('recovers malformed persisted state',()=>{localStorage.setItem('clearstep','bad');render(<App/>);expect(screen.getByLabelText('Daily loss limit ($)')).toHaveValue('300');});
 it('rejects foreign reviewed IDs',()=>{localStorage.setItem('clearstep',JSON.stringify({reviewed:[1,999,'2'],limit:-1}));render(<App/>);expect(screen.getByText('1 of 5 reviewed')).toBeInTheDocument();expect(screen.getByLabelText('Daily loss limit ($)')).toHaveValue('300');});
});
